/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mtxkmkgorwowpwihbgqd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10eGtta2dvcndvd3B3aWhiZ3FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNjEyODAsImV4cCI6MjA3NDczNzI4MH0.1N1WANtzWlQooj_4t-wSisZZLgn-HUhpZDVvrwXIskQ"